pipeline {

    agent any

    stages {
        
         stage("Checkout scm") {

             steps {
                echo 'my first jenkins job'
             }

         }

         stage("Run API tests") {

             steps {
                echo 'my first jenkins job'
             }

         }

         stage("Publish API test results") {

             steps {
                echo 'my first jenkins job'
             }

         }

         stage("Run FE tests") {

             steps {
                echo 'my first jenkins job'
             }

         }

         stage("Publish FE test results ") {

             steps {
                echo 'my first jenkins job'
             }

         }

    }
}