pipeline {

    agent any
    tools {nodejs "node15"}

    stages {
        
         stage("Run cypress tests") {

             steps { 
                echo 'Run cypress api and fromtend tests'
                sh "npm install cypress"
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh "cypress run --reporter mochawesome"
                    echo 'tests failed'
                }
             }

         }

         stage("Publish Test results ") {

             steps {
                echo 'Publishing Test results'
                publishHTML target : [
                    allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'mochawesome-report',
                    reportFiles: 'mochawesome.html',
                    reportName: 'Test Results',
                ]
             }
         }

    }
}